### ISSUE TITLE
[BUG] Le projet "Rushes" n'apparaît pas dans le calculateur

### ISSUE THREAD

**Issue by SimonCROS** [Sylrelo/42Tools#4]
**Describe the bug**
Le projet [https://projects.intra.42.fr/projects/42cursus-rushes](Rushes (https://projects.intra.42.fr/projects/42cursus-rushes)) n'est pas affiché dans la recherche des projets du calculateur.

**Screenshots**
![image](https://github.com/Sylrelo/42Tools/assets/52134884/bb181eed-3dd7-41fd-9a6c-3eaebc759cd9)

**Additional context**
N/A

**Comment by Sylrelo** [comment]
Problème d'update sur les project_session, ça arrive !

**Comment by Sylrelo** [comment]
![image](https://github.com/Sylrelo/42Tools/assets/21089555/2a266c5b-331a-4b75-9ed9-530db20c7e95)

C'est en cours !
En plus d'avoir oublié de programmer le job pour qu'il s'éxecute toute les semaines, j'avais aussi mis le mauvais ordre de tri venant de l'API 42, du coup ça s'updatais jamais 🤡 


Fixed in https://github.com/Sylrelo/42Tools/commit/d8161804753a22646e62bd620b36d774f433f16d
